// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package internal

import (
	"os"

	"massrouter.ai/backend/internal/config"
	"massrouter.ai/backend/internal/controller/admin"
	"massrouter.ai/backend/internal/controller/auth"
	"massrouter.ai/backend/internal/controller/billing"
	"massrouter.ai/backend/internal/controller/health"
	"massrouter.ai/backend/internal/controller/model"
	proxyController "massrouter.ai/backend/internal/controller/proxy"
	"massrouter.ai/backend/internal/controller/user"
	"massrouter.ai/backend/internal/repository"
	"massrouter.ai/backend/internal/service"
	pkgAuth "massrouter.ai/backend/pkg/auth"
	"massrouter.ai/backend/pkg/cache"
	"massrouter.ai/backend/pkg/database"

	"github.com/rs/zerolog"
)

func parseLogLevel(level string) zerolog.Level {
	switch level {
	case "debug":
		return zerolog.DebugLevel
	case "info":
		return zerolog.InfoLevel
	case "warn":
		return zerolog.WarnLevel
	case "error":
		return zerolog.ErrorLevel
	case "fatal":
		return zerolog.FatalLevel
	default:
		return zerolog.InfoLevel
	}
}

func setupLogger(cfg config.LogConfig) zerolog.Logger {
	zerolog.SetGlobalLevel(parseLogLevel(cfg.Level))

	logger := zerolog.New(os.Stdout).With().Timestamp().Logger()

	if cfg.Format == "json" {
		logger = logger.Output(zerolog.NewConsoleWriter())
	}

	return logger
}

// InitializeServer is a manually implemented version of the wire-generated function.
func InitializeServer(cfg *config.Config) (*Server, error) {
	// Setup logger
	logger := setupLogger(cfg.Log)

	// Setup database
	db, err := database.NewPostgresDB(database.Config{
		Host:     cfg.Database.Host,
		Port:     cfg.Database.Port,
		User:     cfg.Database.User,
		Password: cfg.Database.Password,
		DBName:   cfg.Database.DBName,
		SSLMode:  cfg.Database.SSLMode,
	})
	if err != nil {
		return nil, err
	}

	// Setup Redis
	redisClient, err := cache.NewRedisClient(cache.Config{
		Host:     cfg.Redis.Host,
		Port:     cfg.Redis.Port,
		Password: cfg.Redis.Password,
		DB:       cfg.Redis.DB,
	})
	if err != nil {
		return nil, err
	}

	// Setup JWT manager
	jwtManager := pkgAuth.NewJWTManager(
		cfg.JWT.Secret,
		cfg.JWT.AccessExpiry,
		cfg.JWT.RefreshExpiry,
		cfg.JWT.Issuer,
	)

	// Initialize repositories
	userRepo := repository.NewUserRepository(db.DB)
	modelRepo := repository.NewModelRepository(db.DB)
	modelProviderRepo := repository.NewModelProviderRepository(db.DB)
	userAPIKeyRepo := repository.NewUserAPIKeyRepository(db.DB)
	billingRepo := repository.NewBillingRecordRepository(db.DB)
	paymentRepo := repository.NewPaymentRecordRepository(db.DB)
	statisticRepo := repository.NewModelStatisticRepository(db.DB)
	configRepo := repository.NewSystemConfigRepository(db.DB)

	// Initialize quota repositories
	quotaRepo := repository.NewUserQuotaRepository(db.DB)
	usageRepo := repository.NewUserUsageRepository(db.DB)
	monthlyRepo := repository.NewMonthlyUsageRepository(db.DB)

	// Initialize services
	authService := service.NewAuthService(userRepo, jwtManager)
	userService := service.NewUserService(userRepo, userAPIKeyRepo, billingRepo, paymentRepo)
	modelService := service.NewModelService(modelRepo, modelProviderRepo, statisticRepo)
	billingService := service.NewBillingService(paymentRepo, billingRepo, modelRepo, redisClient)
	adminService := service.NewAdminService(
		userRepo, userAPIKeyRepo, paymentRepo, billingRepo,
		modelRepo, modelProviderRepo, statisticRepo, configRepo,
	)

	// Initialize quota service
	quotaService := service.NewQuotaService(quotaRepo, usageRepo, monthlyRepo)

	// Initialize controllers
	healthController := health.NewController(db, redisClient)
	authController := auth.NewController(authService)
	userController := user.NewController(userService, authService, billingService)
	modelController := model.NewController(modelService)
	billingController := billing.NewController(billingService)
	adminController := admin.NewController(adminService)
	proxyController := proxyController.NewController(modelService, billingService, quotaService)

	// Create and return server
	return NewServer(
		cfg,
		logger,
		db,
		redisClient,
		jwtManager,
		healthController,
		authController,
		userController,
		modelController,
		billingController,
		adminController,
		proxyController,
		billingService,
	), nil
}
